apiVersion: apps/v1
kind: Deployment
metadata:
  name: scholarhub-backend
  namespace: scholarhub
spec:
  replicas: 1
  selector:
    matchLabels:
      app: scholarhub-backend
  template:
    metadata:
      labels:
        app: scholarhub-backend
    spec:
      containers:
      - name: django
        image: scholarhub-backend:v6
        imagePullPolicy: IfNotPresent # PENTING: Gunakan image lokal yg baru kita build
        ports:
        - containerPort: 8000
        env:
        # --- KONEKSI VAULT (Sesuai source: 53) ---
        - name: VAULT_ADDR
          value: "http://vault.scholarhub.svc.cluster.local:8200"
        - name: VAULT_ROLE_ID
          value: "4c7be204-b773-7486-8cbc-dc4c6dea263d"  # <--- MASUKKAN ROLE ID DISINI
        - name: VAULT_SECRET_ID
          value: "080a152c-44d8-bcba-2841-78584283de0d" # <--- MASUKKAN SECRET ID DISINI
        
        # --- KONEKSI DATABASE ---
        - name: DB_HOST
          value: "mariadb.scholarhub.svc.cluster.local"
          
        # --- SECURITY & CONFIG ---
        - name: DJANGO_ALLOWED_HOSTS
          value: "*"

---
# --- SERVICE (Agar bisa diakses) ---
apiVersion: v1
kind: Service
metadata:
  name: scholarhub-backend
  namespace: scholarhub
spec:
  type: LoadBalancer 
  selector:
    app: scholarhub-backend
  ports:
  - protocol: TCP
    port: 8000
    targetPort: 8000