apiVersion: apps/v1
kind: Deployment
metadata:
  name: scholarhub-backend
  namespace: scholarhub
spec:
  replicas: 1
  selector:
    matchLabels:
      app: scholarhub-backend
  template:
    metadata:
      labels:
        app: scholarhub-backend
    spec:
      containers:
      - name: django
        image: scholarhub-backend:v12
        imagePullPolicy: IfNotPresent # PENTING: Gunakan image lokal yg baru kita build
        ports:
        - containerPort: 8000
        env:
        # --- KONEKSI VAULT (Sesuai source: 53) ---
        - name: VAULT_ADDR
          value: "http://vault.scholarhub.svc.cluster.local:8200"
        - name: VAULT_ROLE_ID
          value: "8d7a2cbc-0e01-6e70-43b4-7a27361f1c6a"  # <--- MASUKKAN ROLE ID DISINI
        - name: VAULT_SECRET_ID
          value: "bc04f4f5-4431-be69-179f-4f97f23d84ea" # <--- MASUKKAN SECRET ID DISINI
        
        # --- KONEKSI DATABASE ---
        - name: DB_HOST
          value: "mariadb.scholarhub.svc.cluster.local"
          
        # --- SECURITY & CONFIG ---
        - name: DJANGO_ALLOWED_HOSTS
          value: "*"

---
# --- SERVICE (Agar bisa diakses) ---
apiVersion: v1
kind: Service
metadata:
  name: scholarhub-backend
  namespace: scholarhub
spec:
  type: LoadBalancer 
  selector:
    app: scholarhub-backend
  ports:
  - protocol: TCP
    port: 8000
    targetPort: 8000